/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const IPoint = t.iface([], {
  "x": "number",
  "y": "number",
});

export const IPointList = t.iface([], {
  "x": t.array("number"),
  "y": t.array("number"),
});

const exportedTypeSuite: t.ITypeSuite = {
  IPoint,
  IPointList,
};
export default exportedTypeSuite;
