/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const ISerialisedState = t.iface([], {
  "maxY": "number",
  "tension": "number",
  "alpha": "number",
  "points": t.array("IPoint"),
});

const exportedTypeSuite: t.ITypeSuite = {
  ISerialisedState,
};
export default exportedTypeSuite;
